# Generated by Django 5.1.6 on 2025-10-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options_product_image1_product_image2_and_more'),
        ('registration', '0003_user_college_name_user_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='User interested in buying the product', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to='registration.user')),
                ('product', models.ForeignKey(help_text='Product being discussed', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='products.product')),
                ('seller', models.ForeignKey(help_text='User who owns/sells the product', on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to='registration.user')),
            ],
            options={
                'db_table': 'chat_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='registration.user')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='chat_conver_updated_1f6ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer', 'seller'], name='chat_conver_buyer_i_d04d95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('buyer', 'seller', 'product')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
    ]
