# Generated by Django 5.1.6 on 2025-10-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False, help_text='Whether this is a system-generated message (e.g., OTP)'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('regular', 'Regular Message'), ('otp_handover', 'Handover OTP'), ('otp_return', 'Return OTP'), ('system', 'System Notification')], default='regular', help_text='Type of message', max_length=20),
        ),
    ]
