# Generated by Django 5.1.6 on 2025-10-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_system_message_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('regular', 'Regular Message'), ('otp_handover', 'Handover OTP'), ('otp_return', 'Return OTP'), ('otp_handover_notification', 'Handover OTP Notification'), ('otp_return_notification', 'Return OTP Notification'), ('system', 'System Notification')], default='regular', help_text='Type of message', max_length=30),
        ),
    ]
