# Generated by Django 5.1.6 on 2025-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('regular', 'Regular Message'), ('otp_handover', 'Handover OTP'), ('otp_return', 'Return OTP'), ('system', 'System Notification')], default='regular', help_text='Type of message', max_length=20),
        ),
    ]
