# Generated by Django 5.1.6 on 2025-10-20 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_image1_product_image2_and_more'),
        ('registration', '0003_user_college_name_user_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='borrow_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Refundable deposit amount in INR (₹)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='borrow_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental price in INR (₹)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_currently_borrowed',
            field=models.BooleanField(default=False, help_text='Is this item currently borrowed by someone?'),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'For Sale'), ('lend', 'For Lending'), ('both', 'Sale or Lend')], default='sell', help_text='Whether this item is for sale, lending, or both', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='max_borrow_days',
            field=models.IntegerField(default=30, help_text='Maximum number of days item can be borrowed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in INR (₹) - for selling', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_days', models.IntegerField(help_text='Number of days requested to borrow', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active - Item Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message from borrower to lender', null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost (daily rate × days)', max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount', max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('lender_response', models.TextField(blank=True, help_text='Response message from lender', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests_made', to='registration.user')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests_received', to='registration.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='products.product')),
            ],
            options={
                'verbose_name': 'Borrow Request',
                'verbose_name_plural': 'Borrow Requests',
                'db_table': 'borrow_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
