# Generated by Django 5.1.6 on 2025-10-21 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_borrow_deposit_product_borrow_price_per_day_and_more'),
        ('registration', '0003_user_college_name_user_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(help_text='Original product ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=20)),
                ('listing_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('sold', 'Sold')], help_text='Type of action performed', max_length=20)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for deletion or update', null=True)),
                ('views_at_action', models.IntegerField(default=0)),
                ('was_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='registration.user')),
            ],
            options={
                'verbose_name': 'Product History',
                'verbose_name_plural': 'Product Histories',
                'db_table': 'product_history',
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['user', '-action_date'], name='product_his_user_id_76d766_idx'), models.Index(fields=['product_id'], name='product_his_product_85fda1_idx')],
            },
        ),
    ]
