# Generated by Django 5.1.6 on 2025-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='handover_otp',
            field=models.CharField(blank=True, help_text='OTP for item handover verification (lender to borrower)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='handover_otp_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the handover OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='handover_verified_at',
            field=models.DateTimeField(blank=True, help_text='When borrower verified the handover OTP', null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='handover_verified_by_borrower',
            field=models.BooleanField(default=False, help_text='Has borrower confirmed receipt with OTP?'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_otp',
            field=models.CharField(blank=True, help_text='OTP for item return verification (borrower to lender)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_otp_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the return OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_verified_at',
            field=models.DateTimeField(blank=True, help_text='When lender verified the return OTP', null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_verified_by_lender',
            field=models.BooleanField(default=False, help_text='Has lender confirmed return with OTP?'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved - Awaiting Handover'), ('rejected', 'Rejected'), ('active', 'Active - Item Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
