# Generated by GitHub Copilot on 2025-10-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_borrowrequest_handover_otp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove old OTP fields from BorrowRequest
        migrations.RemoveField(
            model_name='borrowrequest',
            name='handover_otp',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='handover_otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='handover_verified_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='handover_verified_by_borrower',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='return_otp',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='return_otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='return_verified_at',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='return_verified_by_lender',
        ),
        
        # Add new OTP verification fields to BorrowRequest
        migrations.AddField(
            model_name='borrowrequest',
            name='acceptance_otp_verified',
            field=models.BooleanField(default=False, help_text='Whether acceptance OTP has been verified (item pickup confirmed)'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='acceptance_otp_verified_at',
            field=models.DateTimeField(blank=True, help_text='When acceptance OTP was verified', null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_otp_verified',
            field=models.BooleanField(default=False, help_text='Whether return OTP has been verified (item return confirmed)'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_otp_verified_at',
            field=models.DateTimeField(blank=True, help_text='When return OTP was verified', null=True),
        ),
        
        # Create BorrowOTP model
        migrations.CreateModel(
            name='BorrowOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('acceptance', 'Acceptance OTP'), ('return', 'Return OTP')], help_text='Type of OTP - acceptance or return', max_length=20)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been successfully verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiry time (default 15 minutes)')),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum allowed verification attempts')),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='products.borrowrequest')),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified the OTP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrow OTP',
                'verbose_name_plural': 'Borrow OTPs',
                'db_table': 'borrow_otps',
                'ordering': ['-created_at'],
            },
        ),
        
        # Add indexes for BorrowOTP
        migrations.AddIndex(
            model_name='borrowotp',
            index=models.Index(fields=['borrow_request', 'otp_type', '-created_at'], name='borrow_otps_borrow_r_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowotp',
            index=models.Index(fields=['otp_code', 'is_verified'], name='borrow_otps_otp_cod_idx'),
        ),
    ]
