# Generated by Django 5.1.6 on 2025-10-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_fix_borrowotp_verified_by'),
        ('registration', '0003_user_college_name_user_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code for handover verification', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been successfully verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiry time (default 15 minutes)')),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum allowed verification attempts')),
            ],
            options={
                'verbose_name': 'Purchase OTP',
                'verbose_name_plural': 'Purchase OTPs',
                'db_table': 'purchase_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved - Awaiting Pickup'), ('rejected', 'Rejected'), ('completed', 'Completed - Item Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message from buyer to seller', null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Agreed purchase price', max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('seller_response', models.TextField(blank=True, help_text='Response message from seller', null=True)),
                ('handover_otp_verified', models.BooleanField(default=False, help_text='Whether handover OTP has been verified (item transfer confirmed)')),
                ('handover_otp_verified_at', models.DateTimeField(blank=True, help_text='When handover OTP was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='borrowotp',
            new_name='borrow_otps_borrow__14e2eb_idx',
            old_name='borrow_otps_borrow_r_idx',
        ),
        migrations.RenameIndex(
            model_name='borrowotp',
            new_name='borrow_otps_otp_cod_f8996b_idx',
            old_name='borrow_otps_otp_cod_idx',
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active - Item Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseotp',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the OTP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_purchase_otps', to='registration.user'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests_made', to='registration.user'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests_received', to='registration.user'),
        ),
        migrations.AddField(
            model_name='purchaseotp',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='products.purchaserequest'),
        ),
        migrations.AddIndex(
            model_name='purchaseotp',
            index=models.Index(fields=['purchase_request', '-created_at'], name='purchase_ot_purchas_e21419_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseotp',
            index=models.Index(fields=['otp_code', 'is_verified'], name='purchase_ot_otp_cod_23ccd3_idx'),
        ),
    ]
