# Generated by Django 5.1.6 on 2025-11-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_purchaseotp_purchaserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrower_shares_location',
            field=models.BooleanField(default=False, help_text='Whether borrower has agreed to share precise location for this request'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='lender_shares_location',
            field=models.BooleanField(default=False, help_text='Whether lender has agreed to share precise location for this request'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='buyer_shares_location',
            field=models.BooleanField(default=False, help_text='Whether buyer has agreed to share precise location for this request'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='seller_shares_location',
            field=models.BooleanField(default=False, help_text='Whether seller has agreed to share precise location for this request'),
        ),
    ]
