# Generated by Django 5.1.6 on 2025-11-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_add_location_sharing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="lender_live_tracking_enabled",
            field=models.BooleanField(default=False, help_text="Whether lender is currently broadcasting live location"),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="lender_live_latitude",
            field=models.FloatField(blank=True, help_text="Latest live latitude shared by lender", null=True),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="lender_live_longitude",
            field=models.FloatField(blank=True, help_text="Latest live longitude shared by lender", null=True),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="lender_live_updated_at",
            field=models.DateTimeField(blank=True, help_text="When lender last shared live location", null=True),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="seller_live_tracking_enabled",
            field=models.BooleanField(default=False, help_text="Whether seller is currently broadcasting live location"),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="seller_live_latitude",
            field=models.FloatField(blank=True, help_text="Latest live latitude shared by seller", null=True),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="seller_live_longitude",
            field=models.FloatField(blank=True, help_text="Latest live longitude shared by seller", null=True),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="seller_live_updated_at",
            field=models.DateTimeField(blank=True, help_text="When seller last shared live location", null=True),
        ),
    ]
