# Generated by Django 5.1.6 on 2025-11-26 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_live_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='seller_live_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latest live latitude shared by seller', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='seller_live_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latest live longitude shared by seller', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
